import { test } from 'node:test';
import assert from 'node:assert/strict';
import { buildFilePlan } from '../scripts/lib/plan.js';

test('file plan always starts with README.md', () => {
    const files = buildFilePlan({ distribution: 'Web', hidemProfile: false });
    assert.equal(files[0], 'README.md');
    assert.ok(files.includes('README.md'));
});

test('Hidem OFF does not add PROJECT.md or MASTER_PROTOCOL.md', () => {
    const files = buildFilePlan({ distribution: 'Web', hidemProfile: false });
    assert.equal(files.includes('PROJECT.md'), false);
    assert.equal(files.includes('.project_rules/MASTER_PROTOCOL.md'), false);
});

test('Hidem ON adds PROJECT.md and MASTER_PROTOCOL.md after the general core', () => {
    const files = buildFilePlan({ distribution: 'Web', hidemProfile: true });
    const readmeAt = files.indexOf('README.md');
    const projectAt = files.indexOf('PROJECT.md');
    assert.ok(projectAt > readmeAt);
    assert.ok(files.includes('.project_rules/MASTER_PROTOCOL.md'));
});

test('docs/index.md is omitted when no other docs files are planned', () => {
    const files = buildFilePlan({ distribution: 'docs-only', hidemProfile: false });
    assert.deepEqual(files, ['README.md']);
});

test('docs/index.md is included when other docs files are planned', () => {
    const files = buildFilePlan({ distribution: 'Web', hidemProfile: false });
    assert.ok(files.includes('docs/TROUBLESHOOTING.md'));
    assert.ok(files.includes('docs/index.md'));
});

test('AI review prompts are not generated by default', () => {
    const files = buildFilePlan({ distribution: 'Web', hidemProfile: true, aiMaintained: true });
    assert.equal(files.includes('docs/AI_REVIEW_PROMPT.md'), false);
    assert.equal(files.includes('docs/AI_IMPROVEMENT_PROMPT.md'), false);
});

test('AI-maintained projects include AGENTS.md', () => {
    const files = buildFilePlan({ distribution: 'docs-only', aiMaintained: true });
    assert.ok(files.includes('AGENTS.md'));
    assert.equal(files.includes('docs/index.md'), false);
});
